# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Benjamin Morgan
title: 
email: bdmorgan@uchicago.edu
website: www.github.com/bmorgan0921

# Social links
# twitter_username: jekyll
github_username:  bmorgan0921
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: BenjaminMorgan0921
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Benjamin and I am a recent grad from the University of Chicago looking to start my career in quantitative finance.

  I am most skilled in: <mark>Python</mark>, <mark>Quantitative Modeling</mark>, and <mark>Creative Thinking</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interest in quantitative finance, some of my other interests and hobbies are:
   - [Photography](https://www.benjaminmorganphotography.smugmug.com/)
   - Sports: Auburn University and Atlanta Braves
   - Staying Active
   - Reading
# - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
