# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Benjamin Morgan
title: 
email: BenjaminMorgan@ChicagoBooth.edu
# website: www.github.com/bmorgan0921

# Social links
# twitter_username: jekyll
github_username:  bmorgan0921
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: 
linkedin_username: BenjaminMorgan0921
# pinterest_username: jekyll
# youtube_username: 
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Benjamin and this website will hopefully share a little bit more about me. I work at Northern Trust as a Senior Analyst in Risk Analytics and I am currently a candidate for my MBA from The University of Chicago Booth School of Business. I have received previous degrees from The University of Chicago in Financial Mathematics and Auburn University in Finance and Electrical Engineering. Below, you will find a detailed version of my résumé including my current and previous projects, professional experiences, education, and interests. 

  I am most skilled in <mark>Quantitative Modeling</mark> in <mark>Python</mark> and <mark>Risk Management</mark> and I enjoy <mark>Developing Models</mark> and <mark>Problem Solving</mark>. 

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education


# More Section
more_title: Activities & Interests
more_content: | # this will include new lines to allow paragraphs
  Alongside my interest in quantitative finance, some of my other interests and hobbies include:
   - [Photography](https://benjaminmorganphotography.smugmug.com/)
   - Sports: Auburn University and Atlanta Braves
   - Currently Reading: [*Fortune's Children: The Fall of the House of Vanderbilt* by Arthur T. Vanderbilt II](https://www.amazon.com/Fortunes-Children-Fall-House-Vanderbilt/dp/0062224069)
   - Future Reading: [*When Genius Failed: The Rise and Fall of Long-Term Capital Management* by Roger Lowenstein](https://www.amazon.com/When-Genius-Failed-Long-Term-Management/dp/0375758259)
   - Books I've Read: [*Extreme Ownership* by Jocko Willink and Leif Babin](https://www.amazon.com/Extreme-Ownership-U-S-Navy-SEALs-dp-1250183863/dp/1250183863/ref=dp_ob_title_bk), [*Atomic Habits* by James Clear](https://www.amazon.com/Atomic-Habits-Proven-Build-Break/dp/0735211299/ref=sr_1_1?keywords=atomic+habits&qid=1645036591&s=books&sprefix=atomi%2Cstripbooks%2C77&sr=1-1), [*The Great Divorce* by C.S. Lewis](https://www.amazon.com/Great-Divorce-C-S-Lewis/dp/0060652950), [*Covert Cows* by Steve Robinson](https://www.amazon.com/Covert-Cows-Chick-fil-Chicken-Iconic/dp/1400213169), [*Getting Things Done* by David Allen](https://www.amazon.com/Getting-Things-Done-Stress-Free-Productivity-dp-0143126563/dp/0143126563/ref=dp_ob_title_bk), [*In My Words* by Robbie Clark](https://www.amazon.com/My-Words-Robbie-Clark/dp/1514489791), [*Measure What Matters* by John Doerr](https://www.amazon.com/Measure-What-Matters-Google-Foundation/dp/0525536221/ref=tmm_hrd_swatch_0?_encoding=UTF8&qid=&sr=), [*How Not to Be Wrong* by Jordan Ellenberg](https://www.amazon.com/How-Not-Be-Wrong-Mathematical/dp/1594205221/ref=tmm_hrd_swatch_0?_encoding=UTF8&qid=&sr=)
   - Staying Active


#  First Header | Second Header  
#  ------------ | ------------- 
#  Content Cell | Content Cell   

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
