# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Benjamin Morgan
title: 
email: bdmorgan@uchicago.edu
# website: www.github.com/bmorgan0921

# Social links
# twitter_username: jekyll
github_username:  bmorgan0921
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: 
linkedin_username: BenjaminMorgan0921
# pinterest_username: jekyll
# youtube_username: 
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Benjamin and I am a recent grad from the University of Chicago looking to start my career in quantitative finance. Below, you will find a more-detailed version of my résumé including my current and previous projects, professional experiences, education, and interests. 

  I am most skilled in <mark>Python</mark> and <mark>Quantitative Modeling</mark> and I enjoy <mark>Problem Solving</mark> and <mark>Creative Thinking</mark>. Other programming or scripting languages that I am familiar with include: C/C++, MATLAB, R, Excel VBA, and a little bit of web development. 

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education


# More Section
more_title: Activities & Interests
more_content: | # this will include new lines to allow paragraphs
  Alongside my interest in quantitative finance, some of my other interests and hobbies include:
   - [Photography](https://benjaminmorganphotography.smugmug.com/)
   - Sports: Auburn University and Atlanta Braves
   - Currently Reading: [*Measure What Matters* by John Doerr](https://www.amazon.com/Measure-What-Matters-Google-Foundation/dp/0525536221/ref=tmm_hrd_swatch_0?_encoding=UTF8&qid=&sr=)
   - Staying Active

Alongside my interest in quantitative finance, some of my other interests and hobbies include


# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
